version: 2

sources:
    - name: jaffle_shop
      description: This is a replica of the Postgres database used by our app
      database: raw
      schema: jaffle_shop
      tables:
          - name: customers
            description: raw customers data
            columns:
              - name: id
                description: Primary key for customers.
          - name: orders
            description: raw orders data
            columns:
              - name: id
                description: Primary key for orders.
                tests:
                  - unique
                  - not_null